//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum CommandType
{
  MOVE,
  TURN,
  WAIT
}

public struct CommandMetadata
{
  public CommandType type;
  public int speed;
  public int time;
  public int rotation;
}


